kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:18
    commands:
      - npm ci
      - npm run build

  - name: deploy
    image: alpine
    environment:
      SSH_KEY:
        from_secret: maniacbox
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H svg-encoder.com >> ~/.ssh/known_hosts
      - scp -r dist/* ssh-548872-mvogtherr@svg-encoder.com:/kunden/548872_85276/websiten/svg-encoder/
