kind: pipeline
type: docker
name: release-to-prod

trigger:
  event:
    - tag
  ref:
    - refs/tags/v*

steps:
  - name: build
    image: node:18
    commands:
      - npm ci
      - npm run build

  - name: deploy
    image: alpine
    environment:
      SSH_KEY:
        from_secret: maniacbox
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H svg-encoder.com >> ~/.ssh/known_hosts
      - REPO_NAME=$(basename $(pwd))
      - scp -r dist/* ssh-548872-mvogtherr@svg-encoder.com:/kunden/548872_85276/webseiten/svg-encoder/
---
kind: pipeline
type: docker
name: deploy-to-test

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build
    image: node:18
    commands:
      - npm ci
      - npm run build

  - name: deploy-to-test
    image: alpine
    environment:
      NAS_SSH_KEY:
        from_secret: maniacbox
    commands:
      - apk add --no-cache openssh
      - mkdir -p ~/.ssh
      - echo "$NAS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H maniacbox.synology.me >> ~/.ssh/known_hosts
      - export REPO_NAME=$DRONE_REPO_NAME

      # sichere Verzeichnis-Erstellung mit eval
      - ssh -i ~/.ssh/id_rsa mvogtherr@maniacbox.synology.me "mkdir -p /volume1/web/${DRONE_REPO_NAME}"

      # vollständige shell mit if/else
      - |
        if [ "$(ls -A dist/)" ]; then
          echo "📦 Dateien gefunden, beginne Transfer..."
          scp -r dist/* mvogtherr@maniacbox.synology.me:/volume1/web/${DRONE_REPO_NAME}/
        else
          echo "⚠️ Kein Inhalt in dist/, Deployment übersprungen."
        fi