kind: pipeline
type: docker
name: default

steps:
  - name: install & build
    image: node:18
    commands:
      - npm ci
      - npm run build

  - name: deploy
    image: alpine
    commands:
      - apk add openssh
      - scp -r dist/* user@dfhost:/var/www/html
    secrets:
      - source: ssh_key
        target: /root/.ssh/id_rsa
